
export const JSON = 
[
    {"id":1,"nombre":"IX Jornada en Adolescencia (2020)","ano":2020,"descripcion":"Adolescentes ¿enredados? Adolescencia. Reconstrucciones en tiempos de pandemia.","coordinador":"Dra. María Alejandra Martínez, Ginecóloga Infanto-Juvenil.Dra. Romina Espeche, Médica Pediatra, especialista en Adolescencia.","link":"xoY26mGB_xA","activo":true,"expositor":"Dr. Juan Carlos Escobar - Médico Pediatra. Dirección de Adolescencias y Juventudes, MSAL."},{"id":2,"nombre":"","ano":2020,"descripcion":"","coordinador":"Lic. Clara Mayaud, Trabajadora Social. Equipo de Adolescencia del Sanatorio Franchin. Dra. Mariana Molinolo Cionci. Médica Psiquiatra. Equipo de Adolescencia del Sanatorio Franchin.","link":"QOXtqgoOHoQ","activo":true,"expositor":"Lic. Lucía Fainboim. Lic. en Cs. de la Comunicación (UBA). Docente Universitaria y Directora de Educación en Faro Digital."},{"id":3,"nombre":"VIII Jornada en Adolescencia (2019)","ano":2019,"descripcion":"","coordinador":"","link":"MlnApkxMxcY","activo":true,"expositor":""},{"id":4,"nombre":"VII Jornada en Adolescencia (2018)","ano":2018,"descripcion":"","coordinador":"","link":"pY-GF1VAZvI","activo":true,"expositor":""}
]

// [
//     {id:1, nombre:"IX Jornada en Adolescencia (2020)",ano: 2020,descripcion:"Adolescentes ¿enredados? Adolescencia. Reconstrucciones en tiempos de pandemia.", expositor: "Dr. Juan Carlos Escobar - Médico Pediatra. Dirección de Adolescencias y Juventudes, MSAL.", coordinador: "Dra. María Alejandra Martínez, Ginecóloga Infanto-Juvenil.Dra. Romina Espeche, Médica Pediatra, especialista en Adolescencia.", link:"xoY26mGB_xA",activo: true},
//     {id:2, nombre:"",ano: 2020,descripcion:"", expositor: "Lic. Lucía Fainboim. Lic. en Cs. de la Comunicación (UBA). Docente Universitaria y Directora de Educación en Faro Digital.", coordinador: "Lic. Clara Mayaud, Trabajadora Social. Equipo de Adolescencia del Sanatorio Franchin. Dra. Mariana Molinolo Cionci. Médica Psiquiatra. Equipo de Adolescencia del Sanatorio Franchin.", link:"QOXtqgoOHoQ",activo: true},
//     {id:3, nombre:"VIII Jornada en Adolescencia (2019)",ano: 2019,descripcion:"", expositor: "", coordinador: "", link:"MlnApkxMxcY",activo: true},
//     {id:4, nombre:"VII Jornada en Adolescencia (2018)",ano: 2018,descripcion:"", expositor: "", coordinador: "", link:"pY-GF1VAZvI", activo: true},
// ]