
export const JSON = [
    {id:1, tipo:"sindicato", banner:"https://app.uocra.org/banners/bannerSindicato.gif", orden: 1, activo: true},
    {id:2, tipo:"salud", banner:"", orden: 1, activo: true},
    {id:3, tipo:"cultura", banner:"https://app.uocra.org/banners/bannerCultura.gif", orden: 1, activo: true},
    {id:3, tipo:"cultura", banner:"https://app.uocra.org/banners/bannerCultura01.gif", orden: 1, activo: true},
    {id:3, tipo:"cultura", banner:"https://app.uocra.org/banners/bannerCultura02.gif", orden: 1, activo: true},
    {id:4, tipo:"tv", banner:"https://app.uocra.org/banners/bannerTv.gif", orden: 1, activo: true},
    {id:4, tipo:"tv", banner:"https://app.uocra.org/banners/bannerTv01.gif", orden: 1, activo: true},
    {id:4, tipo:"tv", banner:"https://app.uocra.org/banners/bannerTv02.gif", orden: 1, activo: true},
    {id:5, tipo:"moecra", banner:"https://app.uocra.org/banners/bannerMoecra.gif", orden: 1, activo: true},
    {id:6, tipo:"saludSeguridad", banner:"https://app.uocra.org/banners/bannerSaludSeguridad.gif", orden: 1, activo: true},
    {id:7, tipo:"ivt", banner:"https://app.uocra.org/banners/bannerIvt.gif", orden: 1, activo: true},
    {id:8, tipo:"cine", banner:"https://app.uocra.org/banners/bannerCine.gif", orden: 1, activo: true},
    {id:8, tipo:"cine", banner:"https://app.uocra.org/banners/bannerCine01.gif", orden: 1, activo: true},
    {id:8, tipo:"cine", banner:"https://app.uocra.org/banners/bannerCine02.gif", orden: 1, activo: true},
    {id:8, tipo:"cine", banner:"https://app.uocra.org/banners/bannerCine03.gif", orden: 1, activo: true},
    {id:8, tipo:"cine", banner:"https://app.uocra.org/banners/bannerCine04.gif", orden: 1, activo: true},
    {id:8, tipo:"cine", banner:"https://app.uocra.org/banners/bannerCine05.gif", orden: 1, activo: true},
    {id:9, tipo:"adolecencia", banner:"https://app.uocra.org/banners/bannerAdolecencia.gif", orden: 1, activo: true},
    {id:9, tipo:"adolecencia", banner:"https://app.uocra.org/banners/bannerAdolecencia2.gif", orden: 1, activo: true},
    {id:9, tipo:"adolecencia", banner:"https://app.uocra.org/banners/bannerAdolecencia3.gif", orden: 1, activo: true},
    {id:10, tipo:"adicciones", banner:"https://app.uocra.org/banners/bannerAdicciones.gif", orden: 1, activo: true},
    {id:10, tipo:"adicciones", banner:"https://app.uocra.org/banners/bannerAdicciones2.gif", orden: 1, activo: true},
    {id:10, tipo:"adicciones", banner:"https://app.uocra.org/banners/bannerAdicciones3.gif", orden: 1, activo: true},
    {id:10, tipo:"adicciones", banner:"https://app.uocra.org/banners/bannerAdicciones4.gif", orden: 1, activo: true},
    {id:10, tipo:"adicciones", banner:"https://app.uocra.org/banners/bannerAdicciones5.gif", orden: 1, activo: true},
    {id:11, tipo:"hogar", banner:"", orden: 1, activo: true},
    {id:12, tipo:"mujeres", banner:"https://app.uocra.org/banners/bannerMujeres.gif", orden: 1, activo: true},
    {id:13, tipo:"arte", banner:"https://app.uocra.org/banners/bannerArte.gif", orden: 1, activo: true},
    {id:14, tipo:"deportes", banner:"https://app.uocra.org/banners/bannerDeportes.gif", orden: 1, activo: true},
    {id:14, tipo:"deportes", banner:"https://app.uocra.org/banners/bannerDeportes2.gif", orden: 1, activo: true},
    {id:14, tipo:"deportes", banner:"https://app.uocra.org/banners/bannerDeportes3.gif", orden: 1, activo: true},
    {id:15, tipo:"beneficios", banner:"https://app.uocra.org/banners/bannerBeneficios.gif", orden: 1, activo: true},
    {id:16, tipo:"turismo", banner:"https://app.uocra.org/banners/bannerTurismo.gif", orden: 1, activo: true},
    {id:11, tipo:"fundacion", banner:"", orden: 1, activo: true},

]