
export const JSON = [
    {id:1, hotelesId:7 , banner:"https://app.uocra.org/hoteles/cordobaSialdorf.gif", orden: 1, activo: true},
    {id:1, hotelesId:7 , banner:"https://app.uocra.org/hoteles/cordobaSialdorf2.gif", orden: 1, activo: true},
    {id:1, hotelesId:7 , banner:"https://app.uocra.org/hoteles/cordobaSialdorf3.gif", orden: 1, activo: true},
    {id:1, hotelesId:7 , banner:"https://app.uocra.org/hoteles/cordobaSialdorf4.gif", orden: 1, activo: true},
    {id:1, hotelesId:7 , banner:"https://app.uocra.org/hoteles/cordobaSialdorf5.gif", orden: 1, activo: true},
    {id:1, hotelesId:7 , banner:"https://app.uocra.org/hoteles/cordobaSialdorf6.gif", orden: 1, activo: true},
    {id:1, hotelesId:7 , banner:"https://app.uocra.org/hoteles/cordobaSialdorf7.gif", orden: 1, activo: true},
    {id:1, hotelesId:1 , banner:"https://app.uocra.org/hoteles/iguazuAmericano.gif", orden: 1, activo: true},
    {id:1, hotelesId:1 , banner:"https://app.uocra.org/hoteles/iguazuAmericano2.gif", orden: 1, activo: true},
    {id:1, hotelesId:1 , banner:"https://app.uocra.org/hoteles/iguazuAmericano3.gif", orden: 1, activo: true},
    {id:1, hotelesId:1 , banner:"https://app.uocra.org/hoteles/iguazuAmericano4.gif", orden: 1, activo: true},
    {id:1, hotelesId:1 , banner:"https://app.uocra.org/hoteles/iguazuAmericano5.gif", orden: 1, activo: true},
    {id:1, hotelesId:1 , banner:"https://app.uocra.org/hoteles/iguazuAmericano6.gif", orden: 1, activo: true},
    {id:1, hotelesId:2 , banner:"https://app.uocra.org/hoteles/iguazuPirayu.gif", orden: 1, activo: true},
    {id:1, hotelesId:2 , banner:"https://app.uocra.org/hoteles/iguazuPirayu2.gif", orden: 1, activo: true},
    {id:1, hotelesId:2 , banner:"https://app.uocra.org/hoteles/iguazuPirayu3.gif", orden: 1, activo: true},
    {id:1, hotelesId:2 , banner:"https://app.uocra.org/hoteles/iguazuPirayu4.gif", orden: 1, activo: true},
    {id:1, hotelesId:2 , banner:"https://app.uocra.org/hoteles/iguazuPirayu5.gif", orden: 1, activo: true},
    {id:1, hotelesId:2 , banner:"https://app.uocra.org/hoteles/iguazuPirayu6.gif", orden: 1, activo: true},
    {id:1, hotelesId:3 , banner:"https://app.uocra.org/hoteles/iguazuTropical.gif", orden: 1, activo: true},
    {id:1, hotelesId:3 , banner:"https://app.uocra.org/hoteles/iguazuTropical2.gif", orden: 1, activo: true},
    {id:1, hotelesId:3 , banner:"https://app.uocra.org/hoteles/iguazuTropical3.gif", orden: 1, activo: true},
    {id:1, hotelesId:3 , banner:"https://app.uocra.org/hoteles/iguazuTropical4.gif", orden: 1, activo: true},
    {id:1, hotelesId:3 , banner:"https://app.uocra.org/hoteles/iguazuTropical5.gif", orden: 1, activo: true},
    {id:1, hotelesId:4 , banner:"https://app.uocra.org/hoteles/mendozaMendoza.gif", orden: 1, activo: true},
    {id:1, hotelesId:4 , banner:"https://app.uocra.org/hoteles/mendozaMendoza2.gif", orden: 1, activo: true},
    {id:1, hotelesId:4 , banner:"https://app.uocra.org/hoteles/mendozaMendoza3.gif", orden: 1, activo: true},
    {id:1, hotelesId:4 , banner:"https://app.uocra.org/hoteles/mendozaMendoza4.gif", orden: 1, activo: true},
    {id:1, hotelesId:5 , banner:"https://app.uocra.org/hoteles/mendozaProvincial.gif", orden: 1, activo: true},
    {id:1, hotelesId:5 , banner:"https://app.uocra.org/hoteles/mendozaProvincial2.gif", orden: 1, activo: true},
    {id:1, hotelesId:5 , banner:"https://app.uocra.org/hoteles/mendozaProvincial3.gif", orden: 1, activo: true},
    {id:1, hotelesId:5 , banner:"https://app.uocra.org/hoteles/mendozaProvincial4.gif", orden: 1, activo: true},
    {id:1, hotelesId:5 , banner:"https://app.uocra.org/hoteles/mendozaProvincial5.gif", orden: 1, activo: true},
    {id:1, hotelesId:6 , banner:"https://app.uocra.org/hoteles/mendozaPuertaDelSol.gif", orden: 1, activo: true},
    {id:1, hotelesId:6 , banner:"https://app.uocra.org/hoteles/mendozaPuertaDelSol2.gif", orden: 1, activo: true},
    {id:1, hotelesId:6 , banner:"https://app.uocra.org/hoteles/mendozaPuertaDelSol3.gif", orden: 1, activo: true},
    {id:1, hotelesId:6 , banner:"https://app.uocra.org/hoteles/mendozaPuertaDelSol4.gif", orden: 1, activo: true},


]