
export const JSON = [
    {id:1,nombre:"MI SINDICATO",imagen: "MISINDICATO" ,accion:"sindicato"},
    {id:2,nombre:"SALUD",imagen: "SALUD" ,accion:"salud"},
    {id:3,nombre:"CAPACITACION",imagen: 'CURSOS' ,accion:"fundacion"},
    {id:4,nombre:"TEATRO",imagen: 'TEATRO' ,accion:"cultura"},
    {id:5,nombre:"TELEVISION",imagen: 'TV',accion:"tv"},
    {id:6,nombre:"CINE",imagen: 'CINE' ,accion:"cine"},
    {id:7,nombre:"ARTE",imagen: 'ARTE' ,accion:"arte"},
    {id:8,nombre:"VIVIENDA",imagen: 'VIVIENDA' ,accion:"ivt"},
    {id:9,nombre:"DEPORTE",imagen: 'DEPORTE' ,accion:"deportes"},
    {id:10,nombre:"TURISMO",imagen: 'TURISMO' ,accion:"turismo"},
    {id:11,nombre:"BENEFICIO",imagen: 'BENEFICIO' ,accion:"beneficios"},
    {id:12,nombre:"SECCIONAL",imagen: 'SECCIONAL' ,accion:"gremioZonas"},
    {id:13,nombre:"ADOLECENCIA",imagen: 'ADOLECENCIA' ,accion:"adolecencia"},
    {id:14,nombre:"ADICCIONES",imagen: 'ADICCIONES' ,accion:"adicciones"},
    {id:15,nombre:"HOGAR",imagen: 'HOGAR' ,accion:"hogar"},
    {id:16,nombre:"SEGURIDAD",imagen: 'SEGURIDAD' ,accion:"saludSeguridad"},
    {id:17,nombre:"MUJERES",imagen: 'MUJERES' ,accion:"mujeres"},
    {id:18,nombre:"JUVENTUD",imagen: 'JUVENTUDES' ,accion:"moecra"},
    {id:19,nombre:"COMPRAS",imagen: 'COMPRA' ,accion:"moecra"},
    {id:20,nombre:"MACRO",imagen: 'MACRO' ,accion:"macro"},
    {id:21,nombre:"DENUNCIA",imagen: 'DENUNCIA' ,accion:"denunciasFormulario"},

]