
export const JSON = [
    {id:1, tipo:"sindicato", leyenda: "", activo: true},
    {id:2, tipo:"salud", leyenda: "", activo: true},
    {id:3, tipo:"cultura", leyenda: "", activo: true},
    {id:4, tipo:"tv", leyenda: "", activo: true},
    {id:5, tipo:"moecra", leyenda: "", activo: true},
    {id:6, tipo:"saludSeguridad", leyenda: "", activo: true},
    {id:7, tipo:"ivt", leyenda: "<div>El <b>Instituto de Vivienda de los Trabajadores</b> (IVT) se creó el 1 de mayo de 1993 con el objetivo de promover y facilitar el acceso a la vivienda por parte de los trabajadores, mediante el adecuado empleo de aportes, ahorros y otros recursos provenientes del sector público y privado, Nacional y extranjero.</div>", activo: true},
    {id:8, tipo:"cine", leyenda: "", activo: true},
    {id:9, tipo:"adolecencia", leyenda: "", activo: true},
    {id:10, tipo:"adicciones", leyenda: "", activo: true},
    {id:11, tipo:"hogar", leyenda: "", activo: true},
    {id:12, tipo:"mujeres", leyenda: "", activo: true},
    {id:13, tipo:"arte", leyenda: "", activo: true},
    {id:14, tipo:"deportes", leyenda: "<div>El <b>Campo de Deportes UOCRA</b> es un complejo deportivo ubicado en Ruta de la Tradición (ex Camino de Cintura) 6251, que ofrece un espacio de esparcimiento y divertimento al aire libre en familia o con amigos.</div>", activo: true},
    {id:15, tipo:"beneficios", leyenda: "", activo: true},
    {id:16, tipo:"turismo", leyenda: "<div style='text-align:center'>*Disponibilidad esta sujeta a las disposicione<br>oficiales de circulación vinculadas a <br>la pandemia de Covid19.<div>", activo: true},
    {id:17, tipo:"fundacion", leyenda: "", activo: true},
]